USE master;
GO 

DROP DATABASE IF EXISTS dbPizzaHut;
CREATE DATABASE  dbPizzaHut;
GO

USE dbPizzaHut;
GO

--Creamos la Tabla Cliente--

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE (
    IDCLI int  NOT NULL IDENTITY,
    NOMCLI varchar(50)  NOT NULL,
    APECLI varchar(50)  NOT NULL,
    DIRECCLI varchar(60)  NOT NULL,
    TELFCLI char(9)  NOT NULL,
    DNICLI char(8)  NOT NULL,
    ESTCLI char(1)  NOT NULL,
    CODUBI char(6)  NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY  (IDCLI)
);
GO

DROP TABLE IF EXISTS EMPLEADO;
CREATE TABLE EMPLEADO (
    IDEMP int  NOT NULL IDENTITY,
    NOMEMP varchar(60)  NOT NULL,
    APEEMP varchar(60)  NOT NULL,
    DIRECEMP varchar(60)  NOT NULL,
    DNIEMP char(8)  NOT NULL,
    TELFEMP char(9)  NOT NULL,
    TIPEMP char(1)  NOT NULL,
    ESTEMP char(1)  NOT NULL,
    IDSUR int  NOT NULL,
    CONSTRAINT EMPLEADO_pk PRIMARY KEY  (IDEMP)
);
GO

DROP TABLE IF EXISTS FAMILIA;
CREATE TABLE FAMILIA (
    IDFAM int  NOT NULL IDENTITY,
    NOMFAM varchar(60)  NOT NULL,
    DESFAM varchar(70)  NOT NULL,
    CONSTRAINT FAMILIA_pk PRIMARY KEY  (IDFAM)
);
GO

DROP TABLE IF EXISTS SUBFAMILIA;
CREATE TABLE SUBFAMILIA (
    IDSUBFAM int  NOT NULL IDENTITY,
    NOMSUBFAM varchar(60)  NOT NULL,
    DESSUBFAM varchar(80)  NOT NULL,
    STOCKSUBFAM int  NOT NULL,
    PRESUBFAM decimal(8,2)  NOT NULL,
    IDFAM int  NOT NULL,
    IDSUR int  NOT NULL,
    CONSTRAINT SUBFAMILIA_pk PRIMARY KEY  (IDSUBFAM)
);
GO

DROP TABLE IF EXISTS SUCURSAL;
CREATE TABLE SUCURSAL (
    IDSUR int  NOT NULL IDENTITY,
    NOMSUR varchar(60)  NOT NULL,
    CODUBI char(6)  NOT NULL,
    CONSTRAINT SUCURSAL_pk PRIMARY KEY  (IDSUR)
);
GO

DROP TABLE IF EXISTS UBIGEO;
CREATE TABLE UBIGEO (
    CODUBI char(6)  NOT NULL,
    DISUBI varchar(60)  NOT NULL,
    PROUBI varchar(60)  NOT NULL,
    DEPUBI varchar(60)  NOT NULL,
    CONSTRAINT UBIGEO_pk PRIMARY KEY  (CODUBI)
);
GO

DROP TABLE IF EXISTS VENTA;
CREATE TABLE VENTA (
    IDVEN int  NOT NULL IDENTITY,
    FECHVEN date  NOT NULL,
    IDCLI int  NOT NULL,
    ESTVEN char(1)  NOT NULL,
    IDEMP int  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY  (IDVEN)
);
GO

DROP TABLE IF EXISTS VENTADETALLE;
CREATE TABLE VENTADETALLE (
    IDVENDET int  NOT NULL IDENTITY,
    CANTVENDET int  NOT NULL,
    IDVEN int  NOT NULL,
    IDSUBFAM int  NOT NULL,
    CONSTRAINT VENTADETALLE_pk PRIMARY KEY  (IDVENDET)
);
GO

-- Relaciones(FOREIGN KEYS)
-- Relaci�n: CLIENTE_UBIGEO (table: CLIENTE)
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_UBIGEO
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI);
GO

-- Relaci�n: EMPLEADO_SUCURSAL (table: EMPLEADO)
ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_SUCURSAL
    FOREIGN KEY (IDSUR)
    REFERENCES SUCURSAL (IDSUR);
GO

-- Relaci�n: SUBFAMILIA_FAMILIA (table: SUBFAMILIA)
ALTER TABLE SUBFAMILIA ADD CONSTRAINT SUBFAMILIA_FAMILIA
    FOREIGN KEY (IDFAM)
    REFERENCES FAMILIA (IDFAM);
GO

-- Relaci�n: SUBFAMILIA_SUCURSAL (table: SUBFAMILIA)
ALTER TABLE SUBFAMILIA ADD CONSTRAINT SUBFAMILIA_SUCURSAL
    FOREIGN KEY (IDSUR)
    REFERENCES SUCURSAL (IDSUR);
GO

-- Relaci�n: SUCURSAL_UBIGEO (table: SUCURSAL)
ALTER TABLE SUCURSAL ADD CONSTRAINT SUCURSAL_UBIGEO
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI);
GO

-- Relaci�n: VENTADETALLE_SUBFAMILIA (table: VENTADETALLE)
ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTADETALLE_SUBFAMILIA
    FOREIGN KEY (IDSUBFAM)
    REFERENCES SUBFAMILIA (IDSUBFAM);
GO

-- Relaci�n: VENTADETALLE_VENTA (table: VENTADETALLE)
ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTADETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);
GO

-- Relaci�n: VENTA_CLIENTE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);
GO

-- Relaci�n: VENTA_EMPLEADO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_EMPLEADO
    FOREIGN KEY (IDEMP)
    REFERENCES EMPLEADO (IDEMP);
GO



INSERT INTO UBIGEO (CODUBI,DISUBI,PROUBI,DEPUBI)
VALUES
('150501','San Vicente','Ca�ete','Lima'),
('150507','Imperial','Ca�ete','Lima'),
('150510','Nvo. Imperial','Ca�ete','Lima');
GO

INSERT INTO FAMILIA (NOMFAM,DESFAM)
VALUES
('Combos','Pizza+gaseosa'),
('Pizzas','solo pizza'),
('Bebidas','solo bebidas');
GO

INSERT INTO CLIENTE (NOMCLI,APECLI,DIRECCLI,TELFCLI,DNICLI,ESTCLI,CODUBI)
VALUES
('Julia Clara','Quispe Avalos','Urb.San Agustin','987654321','16325644','A','150501'),
('Rolando Martin','Alvites Chumpitaz','Av. 28 de Julio','963852741','12345678','A','150501'),
('Dalia Angie','Duran Rojas','Av. 28 de Julio','951357465','10230256','A','150507'),
('Sergio Andrew','Martinez Jimenez','Jr. San Agustin','952145632','10254872','A','150501'),
('Lalo Costa','Rejas Rojas','Calle Santa Rosa','965874698','14858700','A','150501'),
('Kimberly Naomi','Quispe Avalos','Asuncion 8','900326584','10302589','A','150507'),
('Jesus Guilmer','Canales Guando','Calle Principal N�85','963250321','15632541','A','150510'),
('Luis Jesus','Manzo Candela','Av.Ramos Larrea','999632541','20542136','A','150507'),
('Jose Tobey','Dominguez Rivera','Av. La Mar','963200032','10254785','A','150507'),
('Andres Tom','Alvino Saccsa','Tercer Mundo','913205654','10245879','A','150501');
GO


INSERT INTO SUCURSAL (NOMSUR,CODUBI)
VALUES
('Pizza Hut - San Vicente','150501'),
('Pizza Hut - Imperial','150507'),
('Pizza Hut - Nvo. Imperial','150510');
GO


INSERT INTO EMPLEADO (NOMEMP,APEEMP,DIRECEMP,DNIEMP,TELFEMP,TIPEMP,ESTEMP,IDSUR)
VALUES
('Julio Jherry','Quispe Sanchez','Tercer Mundo','12352065','999656662','A','A','1'),
('Jose Alejandro','Zegarra Mamani','Urb. Santa Rosa','15962587','999656462','J','A','1'),
('Darlyn Estefany','Gomez Sulca','Av San Jose','75123645','999645662','V','A','1'),
('Bruce Manuel','Quispe Vargas','Av 28 de Julio','74125896','999656653','D','A','2'),
('Giancarlo Camilo','Valencia Sotomayor','Mercado Chocos','12546381','999656452','A','A','2'),
('Nicolas Daniel','Suarez Juarez','Av. Ayacucho','23652658','988656662','D','A','2'),
('Carlos Fausto','Caceres Huaman','Av. 2 de Mayo','56254163','999651256','J','A','2'),
('Cecilia Leonor','Padilla Cama','Calle Principal N�2','52148751','999656852','D','A','2');
GO

INSERT INTO SUBFAMILIA
VALUES
('Pizza Americana','pizza + hotdog + queso','18','25.00','3','1'),
('Pizza Hawuaiana','pizza + hotdog + queso+ pi�a','16','28.00','3','1'),
('Pizza con extra Queso','pizza + hotdog + champi�ones + extra queso','16','30.00','3','1'),
('Combo 1','pizza americana + gaseosa 2L','8','36.00','1','2'),
('Combo 2','pizza hawuiana+gaseosa 3L.','10','40.00','1','2'),
('Combo 3','pizza familiar + gaseosa 2.5L','4','50.00','1','2'),
('Combo 4','pizza personal + gaseosa 500ml','16','12.50','1','3'),
('Inka Kola 500ml','gaseosa personal','24','3.50','3','3'),
('Coca Cola 3L.','gaseosa familiar','8','12.00','3','3'),
('Coca Cola 2.5L','gaseosa familiar','9','9.00','3','3');
GO


INSERT INTO VENTA
values 
(GETDATE(),'1','E','3'),
(GETDATE(),'2','E','3'),
(GETDATE(),'3','E','2'),
(GETDATE(),'4','E','2');
GO


INSERT INTO VENTADETALLE
VALUES
('2','1','1'),
('2','1','4'),
('3','2','8'),
('1','2','5'),
('2','2','2'),
('3','3','4'),
('1','3','6'),
('1','3','10');
GO


--Creamos los Store Procedures--

CREATE PROCEDURE sp_InsertVenta
(
@IDVEN INT,
@FECHVEN DATE,
@IDCLI INT,
@ESTVEN CHAR(1),
@IDEMP INT
)

AS
	BEGIN
	INSERT INTO VENTA (FECHVEN,IDCLI,ESTVEN,IDEMP)
	VALUES
	(GETDATE(),@IDCLI,@ESTVEN,@IDEMP)

END;
GO

EXEC sp_InsertVenta '','','1','E','2';--ESTVEN (Estado de la venta E= ENVIADO / C=EN CAMINO / R= RECIBIDO)
GO


-- Es vac�o el campo identificador de este Procedure ya que este mismo es autoincrementable--

CREATE PROCEDURE sp_InsertVentaDetalle
	(
	@IDVENDET INT,
	@CANTVENDET INT,
	@IDVEN INT,
	@IDSUBFAM INT
	)
AS
	BEGIN
	INSERT INTO VENTADETALLE(CANTVENDET,IDVEN,IDSUBFAM)
	VALUES
	(@CANTVENDET,@IDVEN,@IDSUBFAM)

END;
GO

EXEC sp_InsertVentaDetalle '','8','5','7';
GO



--Creamos las Vistas--


	CREATE VIEW vVentas
	AS SELECT S.NOMSUR,V.FECHVEN,
	(C.NOMCLI+' '+C.APECLI) AS CLIENTE,
	(E.NOMEMP+' '+E.APEEMP )AS EMPLEADO,
	SB.NOMSUBFAM,VT.CANTVENDET,SB.PRESUBFAM,(SB.PRESUBFAM*VT.CANTVENDET) AS SUBTOTAL
	FROM VENTADETALLE AS VT
	INNER JOIN VENTA AS V
	ON V.IDVEN=VT.IDVEN
	INNER JOIN CLIENTE AS C
	ON C.IDCLI=V.IDCLI
	INNER JOIN EMPLEADO AS E
	ON E.IDEMP=V.IDEMP
	INNER JOIN SUCURSAL AS S
	ON S.IDSUR= E.IDSUR
	INNER JOIN SUBFAMILIA AS SB
	ON SB.IDSUBFAM=VT.IDSUBFAM;
GO

	SELECT V.FECHVEN,V.ESTVEN,(C.NOMCLI+' '+C.APECLI) AS CLIENTES,(E.NOMEMP+' '+E.APEEMP) AS EMPLEADOS,
	S.NOMSUR, SUB.NOMSUBFAM, VT.CANTVENDET,SUB.PRESUBFAM,(SUB.PRESUBFAM*VT.CANTVENDET) AS SUBTOTAL
	FROM VENTADETALLE AS VT
	INNER JOIN SUBFAMILIA AS SUB
	ON  SUB.IDSUBFAM = VT.IDSUBFAM
	INNER JOIN VENTA AS V
	ON V.IDVEN= VT.IDVEN
	INNER JOIN CLIENTE AS C
	ON C.IDCLI= V.IDCLI
	INNER JOIN EMPLEADO AS E
	ON E.IDEMP= V.IDEMP
	INNER JOIN SUCURSAL AS S
	ON S.IDSUR=E.IDSUR	


	SELECT V.IDVEN,S.NOMSUR,V.FECHVEN,
	(C.NOMCLI+' '+C.APECLI) AS CLIENTE,
	(E.NOMEMP+' '+E.APEEMP )AS EMPLEADO,
	SB.NOMSUBFAM,VT.CANTVENDET,SB.PRESUBFAM,(SB.PRESUBFAM*VT.CANTVENDET) AS SUBTOTAL
	FROM VENTADETALLE AS VT
	INNER JOIN VENTA AS V
	ON V.IDVEN=VT.IDVEN
	INNER JOIN CLIENTE AS C
	ON C.IDCLI=V.IDCLI
	INNER JOIN EMPLEADO AS E
	ON E.IDEMP=V.IDEMP
	INNER JOIN SUCURSAL AS S
	ON S.IDSUR= E.IDSUR
	INNER JOIN SUBFAMILIA AS SB
	ON SB.IDSUBFAM=VT.IDSUBFAM;
GO


SELECT * FROM UBIGEO;
GO
SELECT * FROM CLIENTE;
GO
SELECT * FROM SUCURSAL;
GO
SELECT * FROM EMPLEADO;
GO
SELECT * FROM VENTA;
GO
SELECT * FROM VENTADETALLE;
GO
SELECT * FROM FAMILIA;
GO
SELECT * FROM SUBFAMILIA;
GO
SELECT * FROM vVentas;
GO
	